monitor = HDMI-A-1, 2560x1440@144, 0x0, 1
monitor = eDP-1, 1920x1200@60, 2560x0, 1

workspace = 1, monitor:HDMI-A-1
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1

# Theming
exec-once = gsettings set org.gnome.desktop.interface color-scheme prefer-dark
exec-once = gsettings set org.gnome.desktop.interface font-antialiasing rgba
exec-once = gsettings set org.gnome.desktop.interface font-hinting slight
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Colloid-Orange'
exec-once = gsettings set org.gnome.desktop.wm.preferences theme 'Colloid-Orange'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Papirus'
exec-once = gsettings set org.gnome.desktop.interface font-name 'Inter'
exec-once = gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrainsMono NF'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Qogir-white-cursors'
exec-once = hyprctl setcursor Qogir-white-cursors 24

general {
   gaps_in = 2
   gaps_out = 8
   border_size = 2
   layout = dwindle
   col.active_border = rgb(fca062)
   col.inactive_border = rgba(ffffff40)
}

decoration {
   rounding = 10
   rounding_power = 2
   active_opacity = 1
   inactive_opacity = 1
   fullscreen_opacity = 1

   shadow {
      enabled = false
   }

   blur {
      enabled = true
      size = 3
      passes = 3
   }
}

animations {
   enabled = yes

   bezier = myBezier, 0.05, 0.9, 0.1, 1.05

   animation = windows, 1, 5, myBezier, popin 80%
   animation = windowsOut, 1, 5, myBezier, popin 80%
   animation = layers, 1, 5, myBezier, fade
   animation = layersIn, 1, 5, myBezier, fade
   animation = layersOut, 1, 5, myBezier, fade
   animation = fade, 1, 5, myBezier
   animation = workspaces, 1, 5, myBezier, slide
   animation = specialWorkspaceIn, 1, 5, myBezier, fade
   animation = specialWorkspaceOut, 1, 5, myBezier, fade
}


misc {
   force_default_wallpaper = 0
   disable_hyprland_logo = true
   disable_splash_rendering = true
}
