env = GDK_BACKEND, wayland,x11
env = SDL_VIDEODRIVER, wayland
env = CLUTTER_BACKEND, wayland
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1
env = QT_QPA_PLATFORMTHEME, qt5ct
env = GTK_THEME, Colloid
env = XCURSOR_THEME, Qogir-white-cursors
env = XCURSOR_SIZE, 24
