include themes/noctalia.conf

# Kitty Config
symbol_map	U+EA900-U+EA962	madness
font_family	JetBrainsMono NF
font_size        12
italic_font     auto
bold_font       auto
bold_italic_font auto

# The cursor shape can be one of (block, beam, underline)
shell_integration no-cursor
cursor_shape underline
cursor_trail 1

cursor_blink_interval     0.5

window_padding_width 8
allow_remote_control yes
confirm_os_window_close 0

background_opacity 0.3
enable_audio_bell yes
map ctrl+backspace send_text all \x17

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system
